CREATE DATABASE concessionaria;
USE DATABASE concessionaria;
CREATE TABLE cliente (
ID INT NOT NULL AUTO_INCREMENT,
NUM_HABILITACAO VARCHAR(15),
NOME VARCHAR(130),
TELEFONE NUMERIC(15),
ENDERECO VARCHAR(200),
PRIMARY KEY(ID));
CREATE TABLE veiculos (
ID INT NOT NULL AUTO_INCREMENT,
MARCA VARCHAR(20),
COR VARCHAR(15),
MODELO VARCHAR(30),
ANO NUMERIC(10),
PRECO NUMERIC(30),
PRIMARY KEY(ID));
CREATE TABLE venda (
ID_CLIENTE INT NOT NULL,
DATA DATE,
VALOR NUMERIC(30),
ID_VEICULOS INT NOT NULL,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
FOREIGN KEY (ID_VEICULOS) REFERENCES VEICULOS(ID));

